### ISSUE TITLE
It attempted to open a directory as a file and got stuck

### ISSUE THREAD

**Issue by AlysonBasilio** [entropy-research/Devon#32] opened 2024-05-18 14:53 UTC
<img width="1425" alt="image" src="https://github.com/entropy-research/Devon/assets/2593231/8377238e-9d46-43be-9a75-e4280e7224b4">
<img width="1417" alt="image" src="https://github.com/entropy-research/Devon/assets/2593231/88772089-31f9-48c2-8a90-964520d0e991">
<img width="1422" alt="image" src="https://github.com/entropy-research/Devon/assets/2593231/e6a7ebd6-0cd9-4cd1-ae1f-de75a7878dd9">
<img width="1431" alt="image" src="https://github.com/entropy-research/Devon/assets/2593231/3a3728df-7a3a-478b-aa31-aef355586257">

**Comment by killind-dev** [comment] 2024-05-18 18:38
Thanks for opening this! I think I know whats going on.

I think there may need to be some additional error handling around tools, we recently did a large refactor to make working with and adding tools easier.

**Comment by killind-dev** [comment] 2024-05-18 19:24
Hey so I just replicated this @AlysonBasilio. I had it open the devon-tui folder as a file, and it continued to function as normal.

<img width="202" alt="Screenshot 2024-05-18 at 12 20 34 PM" src="https://github.com/entropy-research/Devon/assets/61808204/6892a5e6-32bd-4db0-a5db-0ed5acdb8641">

I'm currently unsure as to the root cause, but by any chance are you running a mac with an M3 processor?

**Comment by AlysonBasilio** [comment] 2024-05-19 13:51
I'm running a mac with an M1 processor

**Comment by dockercore** [comment] 2024-05-21 03:26
me too

**Comment by dockercore** [comment] 2024-05-21 03:26
> I'm running a mac with an M1 processor我正在运行配备 M1 处理器的 Mac

me too

**Comment by akiradev0x** [comment] 2024-05-28 23:30
Should be fixed now, the fix will be available in the next release this week. Just got it to try to open a folder and it did not hang. Closing this issue!

Please open another with debug mode if the issue persists after the next release.

**Closed by akiradev0x** 2024-05-28 23:30 UTC
Labels: 🕹️ issue: agent
